github4ta/GLd-AE1-10-24

pom.xml
добавила зависимости selenium-java, javafaker, rest-assured, junit-jupiter-api в pom.xml
=> set-up-001 добавление зависимостей

src/test/java/by/fiveelement/SearchApiTest.java
Создать в ветке test/java в пакете by.fiveelement
SearchApiTest класс для проверки API запроса
GET https://5element.by/catalog/377-smartfony?digiSearch=true&term=apple&params=%7Csort%3DDEFAULT
1. Отправить запрос
Проверить в ответе
Status Code = 200
=> set-up-001 Тестирование поиска товара

src/test/java/by/fiveelement/ShopsUiTest.java
More detailed requirements.
Адреса Магазинов
Создать в ветке test/java в пакете by.fiveelement
ShopsUiTest класс для проверки
Предварительные шаги
- открыть домашнюю страницу https://5element.by/
- выбрать населенный пункт Минск
- кликнуть на ссылке «Адреса магазинов» (в нижней части (в футере, в подвале) страницы)
- на странице Магазины кликнуть на вкладке Список
1. Адреса магазинов
Проверить
Список магазинов
ул. Корженевского, 26 (ТЦ «Корона», 1 этаж)
пр-т Победителей, 65/1 (ТЦ «Замок», 4 этаж)
пр-т Независимости, 154 (ТЦ «Корона», 1 этаж)
ул. Кальварийская, 24 (ТЦ «Корона», 2 этаж)
ул. Денисовская, 8 (ТЦ «Корона-Сити», 1 этаж)
ул. Монтажников, 2 (Гипермаркет «Евроопт», 1 этаж)
пр-т Партизанский, 79 (ТЦ «Prizma», цокольный этаж)
пр-т Дзержинского, 104-2 (ТЦ «Титан», 1 этаж)
ул. Голубка, …
=> 5E-UI-003 Create test class for checking list of available shop addresses

src/test/java/by/fiveelement/UserRegistrationApiTest.java
Добавила тестовый класс UserRegistrationApiTest со следующими проверками:
-Регистрация без номера телефона;
-Регистрация без имени и номера телефона;
-Регистрация без имени;
-Регистрация с именем в 101 символ
=> 5E-API-002 Тесты регистрации пользователя

src/test/java/by/fiveelement/ForgotPasswordApiRequest.java, src/test/java/by/fiveelement/ForgotPasswordApiTest.java
Добавлены следующие API-тесты для формы восстановление пароля:
1. Пустой логин
2. Отправлен код подтверждения на указанный email
3. Отправлен код подтверждения на указанный номер
4. Неверный логин
=> 5E-API-001

src/test/java/by/fiveelement/RobotPylesosRitmixUiTest.java
Предварительные шаги
- открыть домашнюю страницу https://5element.by/
- выбрать населенный пункт Минск
- в строку поиска ввести «робот-пылесос Ritmix» и нажать на клавиатуре Enter
1. Поиск товара
Проверить что все карточки товаров на странице «Найдено в категориях» содержат фразу
- робот-пылесос Ritmix
=> 5E-UI-005 Поиск товара и проверка соответствия результатов поиска и запроса

src/main/java/conflicts/Main.java
=> refactor conflict Main

src/main/java/conflicts/Main.java, src/main/java/conflicts/Main2.java
add Hello 2 from Polina Erdman.
=> refactor conflict Main2

src/main/java/by/onliner/ui/pages/home/HomePageXpath.java
добавлены XPATH для некоторых элементов футтера на домашней странице
=> add xpath for elements in footer

src/main/java/by/onliner/ui/pages/registration/RegistrationPageXpath.java
Добавил следующие XPATH формы регистрации: 
- для сообщения "или через e-mail";
- для ввода email;
- для ввода пароля;
- для подтверждения пароля;
- для сообщения "Минимум 8 символов".
=> add some XPATH form Registration

src/main/java/by/onliner/ui/pages/registration/RegistrationPageXpath.java
Add xpath to registration page (title, description, social media buttons)
=> add xpath to RegistrationPageXpath

src/main/java/by/onliner/ui/pages/login/LoginPageXpath.java
Добавлены локаторы для веб-элементов:
1. кнопка закрыть
2. кнопка войти
3. поле имя
4. поле пароль
5. текст ("или через ник, e-mail")
=> Локаторы для некоторых веб-элементов логин формы

src/main/java/by/onliner/ui/pages/home/HomePage.java
Добавлены методы:
- возвращающие текст с веб-элемента Вакансии
- выполняющий клик на веб-элементе Манифест
=> ON-UI-504 Добавлены методы

src/main/java/by/onliner/ui/pages/home/HomePage.java
Добавлены методы:
- возвращающие текст с веб-элемента Манифест - getTextManifest();  
- выполняющий клик на веб-элементе Пользовательское соглашение - СlickLinkUserAgreement().
=> add methods getTextManifest(), СlickLinkUserAgreement()

src/main/java/by/onliner/ui/pages/home/HomePage.java, src/main/java/by/onliner/ui/pages/home/HomePageXpath.java
Добавить в класс main/java/by/onliner/ui/pages/home/HomePage.java
методы:
- возвращающие текст с веб-элемента Тарифы (футер)
- выполняющий клик на веб-элементе Вакансии (футер)
=> ON-UI-503 add methods: get text from Tarffs link, click Vacancies link

src/main/java/by/onliner/ui/pages/home/HomePage.java
Кто изменил имя Xpath, поменял в методе
=> refactor methods getSiteRulesLinkText(), clickLinkPublicContracts() 

src/main/java/by/onliner/ui/pages/home/HomePage.java
- getTextUserSupportLink()
- clickLinkUserAgreement()
=> add methods 

src/main/java/by/onliner/ui/pages/home/HomePage.java, src/test/java/by/onliner/ui/HomePageTest.java
добавлен тест testDisplayTextPersonalDataProcessingPolicy
добавлен метод getTextPersonalDataProcessingPolicy
=> ON-UI-616 тест testDisplayTextPersonalDataProcessingPolicy

src/main/java/by/onliner/ui/pages/login/LoginPageXpath.java
Added lokators for the next elements:
1. Link: "Зарегистрироваться на Onliner".
2. Link: "Я не помню пароль".
3. Footer.
=> ON-UI-008 - Add xpathes for element on Auth-form 

src/main/java/by/onliner/ui/pages/home/HomePage.java
ON-UI-510
Добавлены методы:
- возвращающие текст с веб-элемента Правила возврата getTextReturnPolicy
- выполняющий клик на веб-элементе О компании clickAboutCompanyLink
=> добавлены методы clickAboutCompanyLink, getTextReturnPolicy

src/test/java/by/onliner/ui/HomePageTest.java
Добавить в класс test/java/by/onliner/ui/HomePageTest.java
тест проверки, что на Домашней странице
**- есть текст Правила возврата (ссылка в футере страницы)**
=> ON-UI-617 HomePageTest - ReturnPolicy link

src/test/java/by/onliner/ui/HomePageTest.java
Добавить в класс test/java/by/onliner/ui/HomePageTest.java
тест проверки, что на Домашней странице
- есть текст Манифест (ссылка в футере страницы)
=> ON-UI-614 add testDisplayManifestLink

src/main/java/by/onliner/ui/pages/home/HomePage.java, src/test/java/by/onliner/ui/HomePageTest.java
refactor Homepage, add testDisplayPublicContractsLink to HomePageTest
=> ON-UI-618 

src/main/java/by/onliner/ui/pages/login/LoginPage.java, src/main/java/by/onliner/ui/pages/login/LoginPageMessages.java, src/main/java/by/onliner/ui/pages/login/LoginPageXpath.java, src/test/java/by/onliner/ui/LoginPageTest.java
LoginPageTest
Добавить в класс test/java/by/onliner/ui/LoginPageTest.java
тест для проверки, формы логина с пустыми полями
=> ON-UI-640 - Проверка формы логина

src/main/java/by/onliner/ui/pages/home/HomePage.java, src/main/java/by/onliner/ui/pages/home/HousesAndFlatsPage.java, src/test/java/by/onliner/ui/HomePageTest.java
- добаваление теста "Открытие вкладки Дома и квартиры"
=> ON-UI-633 
